### ISSUE TITLE
Error while importing module

### ISSUE THREAD

**Issue by niicojs** [frida/frida-load#3]
Is there some limitation on the version and or api module can use?
I'm trying to import module through require() in a script but it does not work.

For example, require('fs') gives {}, and require('fs-promise') give me an error.

thanks

**Comment by oleavr** [comment]
Correct, not all of Node.js' own modules are available. Note however that newly written code should be using [frida-compile](https://github.com/frida/frida-compile) instead of frida-load. It provides [some builtins](https://github.com/frida/frida-compile/blob/61ad282bca696e3a47bebf521da485802cda9308/index.js#L18-L23) which this (deprecated) module does not.

**Comment by niicojs** [comment]
Ok thanks
I did not saw any reference of frida-compile in docs. I'll try that!

**Comment by niicojs** [comment]
Sorry to bother you again here. In frida-compile there is no babelify preset so it does not get transform much.
Shouldn't it be something like:

```
      b.transform('babelify', {
        presets: ["es2015"],
        sourceMapsAbsolute: !!options.useAbsolutePaths
      });
```
